# Generated by Django 3.2.11 on 2022-02-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0006_alter_inventoryshare_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_share', to='shares.share')),
            ],
        ),
    ]
