# Generated by Django 3.2.11 on 2022-02-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0007_globalinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalinventory',
            options={'ordering': ('share',)},
        ),
        migrations.AlterModelOptions(
            name='inventoryshare',
            options={'ordering': ('owner', 'share')},
        ),
        migrations.AlterModelOptions(
            name='share',
            options={'ordering': ('name',)},
        ),
    ]
