# Generated by Django 3.2.11 on 2022-02-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_inventory_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
