# Generated by Django 3.2.11 on 2022-01-20 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shares', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('current_count', models.IntegerField()),
                ('order_type', models.CharField(max_length=3)),
                ('is_active', models.BooleanField()),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shares.share')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('buyer_offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_offer', to='offer.simpleoffer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller', to=settings.AUTH_USER_MODEL)),
                ('seller_offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_offer', to='offer.simpleoffer')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shares.share')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('current_count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order_type', models.CharField(max_length=3)),
                ('is_active', models.BooleanField()),
                ('share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shares.share')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
