# Generated by Django 3.2.11 on 2022-01-20 18:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trade',
            new_name='SimpleTrade',
        ),
    ]
