# Generated by Django 3.2.11 on 2022-01-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_rename_trade_simpletrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpletrade',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='premiumoffer',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='premiumoffer',
            name='current_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='premiumoffer',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simpleoffer',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simpleoffer',
            name='current_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simpletrade',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
