# Generated by Django 3.2.11 on 2022-01-31 20:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shares', '0002_auto_20220131_2335'),
        ('offer', '0003_auto_20220131_2335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimpleTrade',
            new_name='Trade',
        ),
    ]
