# Generated by Django 3.2.11 on 2022-01-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_rename_simpletrade_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buyer_offer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trade',
            name='seller_offer',
            field=models.CharField(max_length=255),
        ),
    ]
