# Generated by Django 3.2.11 on 2022-02-02 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shares', '0004_auto_20220202_1842'),
        ('offer', '0006_alter_simpleoffer_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumoffer',
            name='share',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shares.share'),
        ),
        migrations.AlterField(
            model_name='premiumoffer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='simpleoffer',
            name='share',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shares.share'),
        ),
        migrations.AlterField(
            model_name='simpleoffer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trade',
            name='share',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shares.share'),
        ),
    ]
