# Generated by Django 3.2.11 on 2022-02-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_auto_20220202_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumoffer',
            name='order_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4),
        ),
        migrations.AlterField(
            model_name='simpleoffer',
            name='order_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4),
        ),
    ]
